CREATE DATABASE TrabajoPractico0
GO
USE TrabajoPractico0
GO
CREATE TABLE Area(
IdArea INT NOT NULL PRIMARY KEY IDENTITY(10,10),
Nombre VARCHAR(50) NOT NULL,
Mail VARCHAR(30) NOT NULL,
Presupuesto BIGINT NOT NULL,
)
GO
CREATE TABLE Empleados(
Legajo BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL,
IdArea INT NOT NULL  FOREIGN KEY REFERENCES Area(IdArea),
Salario MONEY NOT NULL,
FechaContratacion DATE NOT NULL,
FechaBaja DATE,
)
GO
CREATE TABLE Proyectos(
IdProyecto INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
FechaAlta DATE NOT NULL,
FechaBaja DATE,
)
GO
CREATE TABLE Empleado_Proyecto(
IdProyecto INT NOT NULL FOREIGN KEY REFERENCES Proyectos(IdProyecto),
Legajo BIGINT NOT NULL FOREIGN KEY REFERENCES Empleados(Legajo),
PRIMARY KEY(Legajo, IdProyecto),
)
GO